# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_class', models.CharField(choices=[('1', 'individuals'), ('2', 'corporations'), ('3', 'unincorporated business'), ('4', 'trade union'), ('5', 'non-profit organizations'), ('6', 'other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ContributorIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContributorOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date on which the contribution was received', verbose_name='Date')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='data.Contributor')),
            ],
        ),
        migrations.CreateModel(
            name='ElectoralDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('boundary_set', models.CharField(choices=[('2008', '2008')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Filer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(choices=[('BC LIBERAL PARTY', 'Liberal'), ('BC NDP', 'NDP')], max_length=16)),
                ('type', models.CharField(choices=[('CANDIDATE', 'candidate'), ('CONSTITUENCY', 'constituency'), ('ASSOCIATION', 'association'), ('POLITICAL PARTY', 'political party')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('electoral_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filers', to='data.ElectoralDistrict')),
            ],
        ),
        migrations.CreateModel(
            name='UniqueIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='filer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='data.Filer'),
        ),
        migrations.AddField(
            model_name='contributororganization',
            name='unique_organizations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.UniqueOrganization'),
        ),
        migrations.AddField(
            model_name='contributorindividual',
            name='unique_individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.UniqueIndividual'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.ContributorIndividual'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.ContributorOrganization'),
        ),
    ]
