# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filer',
            name='electoral_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filers', to='data.ElectoralDistrict'),
        ),
    ]
