# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20160806_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filer',
            name='affiliation',
            field=models.CharField(choices=[('BC LIBERAL PARTY', 'Liberal'), ('BC NDP', 'NDP')], max_length=40),
        ),
    ]
