# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20160806_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.FloatField(verbose_name='Amount'),
        ),
    ]
