# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20160810_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributororganization',
            old_name='unique_organizations',
            new_name='unique_organization',
        ),
    ]
